import jsPDF from "jspdf";

// We would typically embed a base64 string of the Nastaliq font here
// For demonstration, we assume standard jsPDF behavior, but in a real app,
// you must add the font via doc.addFileToVFS() and doc.addFont()
// example: 
// import { NotoNastaliqUrdu } from './fonts/NotoNastaliqUrdu-Regular-normal.js';

export async function generateBilingualPrescription(patientData: any, medications: any[], doctorData: any) {
  // Create a new jsPDF document
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  // Example placeholder for font embedding (Required for actual Urdu text)
  // doc.addFileToVFS("NotoNastaliqUrdu.ttf", NotoNastaliqUrdu);
  // doc.addFont("NotoNastaliqUrdu.ttf", "UrduFont", "normal");
  
  // Header
  doc.setFontSize(22);
  doc.setTextColor(0, 51, 102);
  doc.text(doctorData?.clinicName || "Aluhic Clinic", 105, 20, { align: "center" });
  
  doc.setFontSize(12);
  doc.setTextColor(100, 100, 100);
  doc.text(`Dr. ${doctorData?.name || "Doctor"}`, 105, 28, { align: "center" });
  doc.text(doctorData?.specialty || "General Physician", 105, 34, { align: "center" });
  
  doc.setLineWidth(0.5);
  doc.setDrawColor(200, 200, 200);
  doc.line(10, 40, 200, 40);

  // Patient Info
  doc.setFontSize(10);
  doc.setTextColor(0, 0, 0);
  doc.text(`Patient Name: ${patientData?.name || "Walk-in Patient"}`, 15, 50);
  doc.text(`Age/Sex: ${patientData?.age || "--"} / ${patientData?.gender || "--"}`, 15, 56);
  doc.text(`Date: ${new Date().toLocaleDateString()}`, 150, 50);
  
  // Rx Symbol
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.text("Rx", 15, 70);

  // Medications
  doc.setFont("helvetica", "normal");
  let yPos = 85;

  medications.forEach((med, index) => {
    // English Name
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text(`${index + 1}. ${med.medicineName} (${med.dosage || ""})`, 15, yPos);
    
    // Quantity
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    if (med.quantity) {
      doc.text(`Qty: ${med.quantity}`, 150, yPos);
    }
    
    yPos += 8;

    // Instructions (English & Urdu)
    doc.setTextColor(50, 50, 50);
    const engInstruction = `${med.frequency || ""} - ${med.duration || ""} | ${med.instructions || ""}`;
    doc.text(engInstruction, 25, yPos);
    
    // Urdu Instruction Simulation
    // In production, doc.setFont("UrduFont") is required
    yPos += 7;
    const urduInstruction = `${med.frequencyUrdu || ""} - ${med.durationUrdu || ""} | ${med.instructionsUrdu || ""}`;
    
    // We align Right for RTL text
    // doc.text(urduInstruction, 195, yPos, { align: "right" });
    // For now we just print it. Some PDF renderers need special RTL plugins.
    doc.text(urduInstruction, 195, yPos, { align: "right" });

    yPos += 12;
    doc.setTextColor(0, 0, 0);
  });

  // Footer
  doc.line(10, 275, 200, 275);
  doc.setFontSize(9);
  doc.setTextColor(150, 150, 150);
  doc.text("Generated by Aluhic Prescription Management System", 105, 282, { align: "center" });

  // Save the PDF
  doc.save(`Prescription_${patientData?.name?.replace(/\s+/g, '_') || "Patient"}_${Date.now()}.pdf`);
}
